# Generated by Django 5.2.10 on 2026-02-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_notarized',
            field=models.DateField(blank=True, null=True),
        ),
    ]
