# Generated by Django 5.2.10 on 2026-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_date_notarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='procuring_entity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='project_entity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='sales_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
