# Generated by Django 5.2.10 on 2026-02-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='door_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
