# Generated by Django 5.2.10 on 2026-02-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_envelope_door_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='door_number',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='procuring_entity',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='project_entity',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='sales_name',
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='EnvelopeMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_entity', models.CharField(blank=True, max_length=200, null=True)),
                ('procuring_entity', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_name', models.CharField(blank=True, max_length=200, null=True)),
                ('door_number', models.CharField(blank=True, max_length=50, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_details', to='core.envelope')),
            ],
        ),
    ]
