# Generated by Django 5.2.10 on 2026-02-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='envelopemeta',
            name='door_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envelopemeta',
            name='procuring_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envelopemeta',
            name='project_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envelopemeta',
            name='sales_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
