# Generated by Django 5.2.10 on 2026-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_action_alter_document_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
