from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Document, Region

class CustomSignupForm(UserCreationForm):
    # Add the extra fields you wanted
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    department = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'department']
        # Adding bootstrap class to the username field automatically generated by Django
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['title', 'content_context', 'num_pages', 'date_notarized']