"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- SECURITY SETTINGS ---
# SECURITY WARNING: keep the secret key used in production secret!
# (On Render, you should ideally set this as an Environment Variable, but this works for now)
SECRET_KEY = 'django-insecure-bw!f7q5l!oloe7ky7v3yzt%-$rj3_71l6$=)3h5kcpa$@6c(sb'

# SECURITY WARNING: don't run with debug turned on in production!
# You can set an Environment Variable 'RENDER' on Render to automatically turn this False
DEBUG = True 

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'greenergy-exgv.onrender.com', # Your Render URL
]


# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    'core', # Your Custom App
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", # <--- Required for Static Files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- DATABASE CONFIGURATION ---
# Logic: Use SQLite by default (Local), but switch to PostgreSQL if on Render.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# This overrides the default if Render provides a DATABASE_URL
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)


# --- PASSWORD VALIDATION ---

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# --- INTERNATIONALIZATION ---

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- AUTH & SESSION SETTINGS ---

AUTH_USER_MODEL = 'core.User'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Session Security
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800 # Auto-logout after 30 minutes
SESSION_SAVE_EVERY_REQUEST = True


# --- STATIC FILES (CSS, JavaScript, Images) ---

STATIC_URL = 'static/'

# Where your local static files live (Greenergy/core/static)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'),
]

# Where Render collects files during deployment (Greenergy/staticfiles)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use WhiteNoise to serve static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# --- DEFAULT AUTO FIELD ---

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'